CONFIG_NETWORKING=y
CONFIG_NET_CONFIG_AUTO_INIT=n
CONFIG_NET_IPV4=y
CONFIG_NET_IPV4_PMTU=y
CONFIG_NET_L2_VIRTUAL=y
CONFIG_NET_PKT_FILTER=y

CONFIG_NET_TC_TX_COUNT=1
CONFIG_NET_L2_ETHERNET_RESERVE_HEADER=y
CONFIG_NET_ARP_TABLE_SIZE=4

CONFIG_NET_DHCPV4=y
CONFIG_NET_HOSTNAME_ENABLE=y
CONFIG_NET_HOSTNAME="vole"
CONFIG_NET_TCP=y
CONFIG_NET_MAX_CONN=10
CONFIG_NET_MAX_CONTEXTS=10

CONFIG_MDNS_RESPONDER=y
CONFIG_HTTP_SERVER=y
CONFIG_HTTP_SERVER_VERSION_1=y
CONFIG_HTTP_SERVER_VERSION_2=n
CONFIG_HTTP_SERVER_MAX_CLIENTS=1
CONFIG_HTTP_SERVER_MAX_STREAMS=1
CONFIG_ZVFS_EVENTFD_MAX=2
CONFIG_ZVFS_POLL_MAX=9

CONFIG_SHELL=y
CONFIG_NET_SHELL=y
CONFIG_SYS_HEAP_RUNTIME_STATS=y

CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y
CONFIG_BASE64=y

CONFIG_GPIO=y
CONFIG_EVENTS=y
CONFIG_REBOOT=y
CONFIG_INPUT=y
CONFIG_INPUT_GPIO_KEYS=y
CONFIG_WATCHDOG=y

CONFIG_LOG=y
CONFIG_LOG_BUFFER_SIZE=2048
# CONFIG_LOG_MODE_MINIMAL=y
# CONFIG_LOG_MODE_IMMEDIATE=y

# CONFIG_NET_LOG=y
# CONFIG_NET_ARP_LOG_LEVEL_DBG=y
# CONFIG_NET_BUF_LOG_LEVEL_DBG=y
# CONFIG_NET_CONN_LOG_LEVEL_DBG=y
# CONFIG_NET_CORE_LOG_LEVEL_DBG=y
# CONFIG_NET_CORE_LOG_LEVEL_INF=y
# CONFIG_NET_DEBUG_NET_PKT_ALLOC=y
# CONFIG_NET_DHCPV4_SERVER_LOG_LEVEL_DBG=y
# CONFIG_NET_HTTP_LOG_LEVEL_DBG=y
# CONFIG_NET_HTTP_SERVER_LOG_LEVEL_DBG=y
# CONFIG_NET_ICMPV4_LOG_LEVEL_DBG=y
# CONFIG_NET_ICMPV6_LOG_LEVEL_DBG=y
# CONFIG_NET_IF_LOG_LEVEL_DBG=y
# CONFIG_NET_IF_LOG_LEVEL_INF=y
# CONFIG_NET_IPV4_LOG_LEVEL_DBG=y
# CONFIG_NET_IPV6_LOG_LEVEL_DBG=y
# CONFIG_NET_L2_ETHERNET_LOG_LEVEL_DBG=y
# CONFIG_NET_L2_ETHERNET_LOG_LEVEL_DBG=y
# CONFIG_NET_L2_ETHERNET_LOG_LEVEL_INF=y
# CONFIG_MDNS_RESPONDER_LOG_LEVEL_DBG=y
# CONFIG_NET_MGMT_EVENT_LOG_LEVEL_WRN=y
# CONFIG_NET_PKT_FILTER_LOG_LEVEL_DBG=y
# CONFIG_NET_PKT_LOG_LEVEL_DBG=y
# CONFIG_NET_ROUTE_LOG_LEVEL_DBG=y
# CONFIG_NET_SOCKETS_LOG_LEVEL_DBG=y
# CONFIG_NET_TCP_LOG_LEVEL_DBG=y
# CONFIG_NET_UTILS_LOG_LEVEL_DBG=y

# CONFIG_WIFI_LOG_LEVEL_DBG=y

# CONFIG_DTLS_LOG_LEVEL_DBG=y
# CONFIG_NPF_LOG_LEVEL_DBG=y
# CONFIG_RA_LOG_LEVEL_DBG=y

# CONFIG_NO_OPTIMIZATIONS=y
# CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_SPEED_OPTIMIZATIONS=y
# CONFIG_DEBUG=y
CONFIG_ASSERT=y
# CONFIG_ASSERT_VERBOSE=y
# CONFIG_STACK_CANARIES=y
# CONFIG_STACK_SENTINEL=y
# CONFIG_FRAME_POINTER=y
# CONFIG_THREAD_STACK_INFO=y
# CONFIG_SYMTAB=y

CONFIG_MAIN_STACK_SIZE=3072
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=3072
CONFIG_NET_RX_STACK_SIZE=3072
CONFIG_NET_TX_STACK_SIZE=3072
# CONFIG_NET_SOCKETS_SERVICE_STACK_SIZE=3072
CONFIG_HTTP_SERVER_STACK_SIZE=4096
CONFIG_NET_MGMT_EVENT_QUEUE_SIZE=6
# CONFIG_NET_MGMT_EVENT_STACK_SIZE=3072

CONFIG_PICOLIBC=y
CONFIG_PICOLIBC_USE_MODULE=y
# For chacha20-poly1305
# CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=14336
# For aes128-ccm-8
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=16384

CONFIG_WOLFSSL_SETTINGS_FILE="wolfssl-settings.h"
CONFIG_WOLFSSL=y
CONFIG_WOLFSSL_BUILTIN=n
# CONFIG_WOLFSSL_DEBUG=y

# CONFIG_VOLE_BENCH=y

# For sojourn time measurement and AQM
CONFIG_NET_PKT_TIMESTAMP=y
# For telemetry
CONFIG_SNTP=y

CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_THREAD_RUNTIME_STACK_SAFETY=y
CONFIG_THREAD_RUNTIME_STACK_SAFETY_DEFAULT_UNUSED_THRESHOLD_PCT=13

CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_ANALYZER_STACK_SAFETY=y
CONFIG_THREAD_ANALYZER_AUTO=y
CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=900
CONFIG_THREAD_ANALYZER_AUTO_STACK_SIZE=2048
