manifest:
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.4.0
      import:
        file: west.yml
        name-allowlist:
          - zephyr
          - hal_espressif
          - mbedtls
          - picolibc
          - tf-psa-crypto

    - name: wolfssl
      url: https://github.com/wolfSSL/wolfssl
      revision: v5.9.1-stable

    - name: tomlc17
      url: https://github.com/cktan/tomlc17
      revision: R260414

    - name: cryptogams
      url: https://github.com/dot-asm/cryptogams
      revision: 680f98c1765a7cb89c193db169ed048599f92186
