manifest:
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: 09ad7174e940fde3bdd2e24214ca249c12a41cb8
      import:
        file: west.yml
        name-allowlist:
          - zephyr
          - hal_espressif
          - mbedtls
          - picolibc
          - tf-psa-crypto

    - name: wolfssl
      url: https://github.com/wolfSSL/wolfssl
      revision: v5.9.0-stable

    - name: tomlc17
      url: https://github.com/cktan/tomlc17
      revision: R260302

    - name: cryptogams
      url: https://github.com/dot-asm/cryptogams
      revision: 680f98c1765a7cb89c193db169ed048599f92186
