apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: P951FEA4DE68E13C5
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: telemetry
      tlsSkipVerify: true
    secureJsonData:
      token: mytoken123
    isDefault: true
    editable: true
