[agent]
  interval = "1s"
  flush_interval = "1s"

[[inputs.execd]]
  command = ["/usr/local/bin/parser.py"]
  signal = "none"
  restart_delay = "5s"
  data_format = "influx"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "mytoken123"
  organization = "myorg"
  bucket = "telemetry"

# Uncomment this section and check out the logs:
#   docker compose restart telegraf
#   docker compose logs -f telegraf
# [[outputs.file]]
#   files = ["stdout"]
#   data_format = "influx"
