# 1. perf record 60000 100
# 2. perf printbuf
# 3. copy to file perf.data
#   Perf buf length 2048
#   0000000000000002
#   000000004080598c
#   ...
#   0000000040805986
# 4. python3 zephyr/scripts/profiling/stackcollapse.py \
#    perf.data build/zephyr/zephyr.elf | FlameGraph/flamegraph.pl >perf.svg

CONFIG_FRAME_POINTER=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_PROFILING=y
CONFIG_PROFILING_PERF=y
CONFIG_PROFILING_PERF_BUFFER_SIZE=20000
