[Interface]
Address = 10.1.0.1/32, fdf7:fa8:ed0c:eeee::1/128
PrivateKey = ppppppppppppppppppppppppppppppppppppppppppp=
ListenPort = nnnnn
MTU = 1420

PostUp  = ip tunnel add he-ipv6 mode sit remote 216.66.80.30 local x.y.z.w ttl 255
PostUp  = ip link set he-ipv6 up mtu 1420
PostUp  = ip addr add 2001:470:qqqq:rrrr::2/64 dev he-ipv6
PostUp  = ip route add ::/0 dev he-ipv6 metric 100

PreDown = ip route del ::/0 dev he-ipv6 metric 100
PreDown = ip addr del 2001:470:qqqq:rrrr::2/64 dev he-ipv6
PreDown = ip link set he-ipv6 down
PreDown = ip tunnel del he-ipv6

[Peer]
PublicKey = PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP=
AllowedIPs = 10.1.0.2/32, 192.168.3.0/24, fdf7:fa8:ed0c:eeee::2/128, 2001:470:qqqq:rrrr::/64

# table inet filter {
#   chain input {
#     type filter hook input priority filter; policy drop;
#     ct state { established, related } counter accept;
#     udp dport { 60885 } counter accept;
#   }
#   chain forward {
#     type filter hook input priority filter; policy drop;
#     ct state { established, related } counter accept;
#     iifname { "wg-vole" } oifname "he-ipv6" counter accept;
#   }
# }
