{
 "title": "Telemetry",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_INFLUXDB" }
  ]
 },
 "panels": [
  {
   "title": "Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"basic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"heap_used\")\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"basic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tx_backlog\")\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Basic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"basic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"allocs_failed\")\n  |> filter(fn: (r) => r[\"host\"] == \"vole\")\n  |> drop(columns: [\"host\"])\n  |> difference()\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"basic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"early_drops\")\n  |> drop(columns: [\"host\"])\n  |> difference()\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"basic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"codel_drop_count\")\n  |> drop(columns: [\"host\"])\n  |> difference()\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"basic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"codel_drop_len\")\n  |> drop(columns: [\"host\"])\n  |> difference()\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Sojourn Time LAN",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sojourn_lan\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.bucket != \"0.1\" and r.bucket != \"0.2\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      bucket: if r.bucket == \"409.6\" then float(v: \"+Inf\") else float(v: r.bucket)\n    }))\n"
    }
   ]
  },
  {
   "title": "Sojourn Time WAN",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sojourn_wan\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.bucket != \"0.1\" and r.bucket != \"0.2\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      bucket: if r.bucket == \"409.6\" then float(v: \"+Inf\") else float(v: r.bucket)\n    }))\n"
    }
   ]
  }
 ]
}